---
default:
  excludes:
    commit_msg:
      - change_id
      - release_note
    pre_commit:
      - causes_email
      - image_optimization
      - restricted_paths
      - test_history
all:
  excludes:
